### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by breakingflower** [cvlab-epfl/tf-lift#36]
Hi 

I've made a docker file that contains all of your code and dependencies. 

```
docker pull fremmen/tf-lift
```

**Comment by coolbeam** [comment]
> Hi
> 
> I've made a docker file that contains all of your code and dependencies.
> 
> ```
> docker pull fremmen/tf-lift
> ```

hello，thanks for your docker, i've pull your docker file and run the code. I have successfully run the first phase: subtask=kp. However, when i'm going to run the second phase: subtask=ori, it turns out: 

[joint] Checking if old pre-trained weights exists in 
[joint] No pretrained weights from the old framework
[joint] Checking if previous Tensorflow run exists in 
[joint] No previous Tensorflow result
[joint] Checking if previous Tensorflow run exists in logs/test/joint
[joint] No previous Tensorflow result
[ori] Checking if old pre-trained weights exists in 
[ori] No pretrained weights from the old framework
[ori] Checking if previous Tensorflow run exists in 
[ori] No previous Tensorflow result
[ori] Checking if previous Tensorflow run exists in logs/test/ori
[ori] No previous Tensorflow result
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 70, in main
    task.run()
  File "/tf-lift/tester.py", line 110, in run
    raise RuntimeError("Could not load network weights!")
RuntimeError: Could not load network weights!

I think maybe something run in the pretrained model ori

**Comment by coolbeam** [comment]
> > Hi
> > I've made a docker file that contains all of your code and dependencies.
> > ```
> > docker pull fremmen/tf-lift
> > ```
> 
> hello，thanks for your docker, i've pull your docker file and run the code. I have successfully run the first phase: subtask=kp. However, when i'm going to run the second phase: subtask=ori, it turns out:
> 
> [joint] Checking if old pre-trained weights exists in
> [joint] No pretrained weights from the old framework
> [joint] Checking if previous Tensorflow run exists in
> [joint] No previous Tensorflow result
> [joint] Checking if previous Tensorflow run exists in logs/test/joint
> [joint] No previous Tensorflow result
> [ori] Checking if old pre-trained weights exists in
> [ori] No pretrained weights from the old framework
> [ori] Checking if previous Tensorflow run exists in
> [ori] No previous Tensorflow result
> [ori] Checking if previous Tensorflow run exists in logs/test/ori
> [ori] No previous Tensorflow result
> Traceback (most recent call last):
> File "main.py", line 98, in
> tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
> _sys.exit(main(_sys.argv[:1] + flags_passthrough))
> File "main.py", line 70, in main
> task.run()
> File "/tf-lift/tester.py", line 110, in run
> raise RuntimeError("Could not load network weights!")
> RuntimeError: Could not load network weights!
> 
> I think maybe something run in the pretrained model ori

hello，thanks for your docker, i've pull your docker file and run the code. 
Thanks a lot! 
The code is all right, I found that if you want to run the pretrained model, you should use: '--logdir=release-aug', not the default '--logdir=logs/test'

**Comment by kmyi** [comment]
Closing, since not a bug

**Comment by kmyi** [comment]
Well, actually, leaving it open since the docker is useful! (thought this was a bug report. Sorry for spam!)

**Comment by breakingflower** [comment]
@coolbeam running the code inside the docker is the same as in the original implementation.
