### ISSUE TITLE
! Problems in running main.py

### ISSUE THREAD

**Issue by kevinsky-chen** [cvlab-epfl/tf-lift#52]
Hi, thank you for sharing this fabulous code!
I've encountered some problems while executing
`python main.py --task=train --subtask=desc`

The error message is down below:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flufl/lock/_lockfile.py", line 202, in lock
    os.link(self._claimfile, self._lockfile)
OSError: [Errno 38] Function not implemented: '.locks/setup.lock|39a239ed6eba|972|4773241702466798304' -> '.locks/setup.lock'
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 59, in main
    task = Trainer(config, rng)
  File "/content/drive/My Drive/ColabNotebooks/stitching/tf-lift/trainer.py", line 71, in __init__
    self.dataset = Dataset(self.config, rng)
  File "/content/drive/My Drive/ColabNotebooks/stitching/tf-lift/datasets/lift.py", line 85, in __init__
    self.data_wrapper = self.data_module.Wrapper(config, rng)
  File "/content/drive/My Drive/ColabNotebooks/stitching/tf-lift/datasets/eccv2016/wrapper.py", line 107, in __init__
    old_data = old_impl.data_obj(param, task)
  File "/content/drive/My Drive/ColabNotebooks/stitching/tf-lift/datasets/eccv2016/eccv.py", line 242, in __init__
    self.load_data(param, mode)
  File "/content/drive/My Drive/ColabNotebooks/stitching/tf-lift/datasets/eccv2016/eccv.py", line 263, in load_data
    pathconf.setupTrain(param, param.dataset.trainSetList[idxSet])
  File "/content/drive/My Drive/ColabNotebooks/stitching/tf-lift/datasets/eccv2016/custom_types.py", line 146, in setupTrain
    lock.lock()
  File "/usr/local/lib/python3.7/dist-packages/flufl/lock/_lockfile.py", line 202, in lock
    os.link(self._claimfile, self._lockfile)
OSError: [Errno 38] Function not implemented: '.locks/setup.lock|39a239ed6eba|972|4773241702466798304' -> '.locks/setup.lock'
Exception ignored in: <function Lock.__del__ at 0x7f2db90e8cb0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flufl/lock/_lockfile.py", line 319, in __del__
  File "/usr/local/lib/python3.7/dist-packages/flufl/lock/_lockfile.py", line 314, in finalize
  File "/usr/local/lib/python3.7/dist-packages/flufl/lock/_lockfile.py", line 271, in unlock
  File "/usr/local/lib/python3.7/dist-packages/flufl/lock/_lockfile.py", line 298, in is_locked
  File "/usr/local/lib/python3.7/dist-packages/flufl/lock/_lockfile.py", line 447, in _touch
ImportError: sys.meta_path is None, Python is likely shutting down

```
- p.s. Installed modules with python3.7 are:
- numpy, h5py, tensorflow==1.14, tensorflow-gpu==1.14
- parse, flufl.lock==3

Can someone help me solve this problem? Thanks a lot!

**Comment by kmyi** [comment]
Hi, this codebase is 4 years old, so it'll be quite tricky to solve. It however seems like there's a bit of an issue in flufl? Perhaps you want to use a different version of it? You can also try the docker file at #36

**Comment by kevinsky-chen** [comment]
> Hi, this codebase is 4 years old, so it'll be quite tricky to solve. It however seems like there's a bit of an issue in flufl? Perhaps you want to use a different version of it? You can also try the docker file at #36

Hi professor, thank you for your instant reply! Do you have something like requirement.txt of this project that includes the dependent module and its edition? It might be more convenient to use. Thanks a lot!!!

**Comment by kmyi** [comment]
Unfortunately no. But the docker file should have the exact configurations required.

**Comment by ghamsarimah** [comment]
Hi professore thank you for sharing your code 
I run your code with this line
python main.py --task=train --subtask=desc
but showing an error
![image](https://user-images.githubusercontent.com/4607732/140492513-4e999c67-f78f-4530-befb-c65a1b6264af.png)
can you help me ?

**Comment by kmyi** [comment]
Seems like there's an OS related error for flufl.lock. You system seems to not support simlinks.
