### ISSUE TITLE
problem of file notfound

### ISSUE THREAD

**Issue by Jinniuzuo0516** [cvlab-epfl/tf-lift#53]
hello,dear professor
when i run this project with  python main.py --task=train --subtask=desc  ,I've gotten error as follows:
OSError: Unable to open file (unable to open file: name = '/scratch/CenterLi24/Temp/ECCV/piccadilly/train/8428245d927bae458f4f074c274fab6d/27ac55ebaf938a736d6027537eb0aa07/1062837605_d2ccc880bf_o.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
I0825 10:01:08.412329  8768 filelock.py:318] Lock 1920118455560 released on .locks/c6739e96140124d897e6aedf75bf23eb

would you please share this file named 1062837605_d2ccc880bf_o.h5 and related files which under file 'scratch'
thank you very much

**Comment by kmyi** [comment]
It's been five years since the code release, so I am not sure, but I think the code is looking for some files necessary for training that you need to create yourself.

**Comment by aditipanda** [comment]
@Jinniuzuo0516 look into https://github.com/4xle/tf-lift

They provide an example of how the training data should look like. 
I am trying to run it.

@kmyi @etrulls  do you have any demo for using VisualSFM on picadilly images?

**Comment by aditipanda** [comment]
@4xle @kmyi @etrulls 

For this step in data pre-processing:
3. Call: VisualSFM.exe pointed at the directory which contains the extracted images.
      Calling the VSFM GUI ensures CUDA usage.

I have downloaded the Piccadilly Image Dataset from  http://www.cs.cornell.edu/projects/1dsfm/.
However, without SIFT features, **how to use VisualSFM with the extracted dataset?**

@4xle I tried using your lift-example-piccadilly to train the descriptor but got stuck at one point: 

-------------------------------------------------
 Training
-------------------------------------------------
_Subtask = desc:   0%|                            | 0/100000000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\hp\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\hp\Anaconda3\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\hp\Anaconda3\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "main.py", line 70, in main
    task.run()
  File "D:\2016-LIFT Learned Invariant Feature Points\tf-lift-master\trainer.py", line 141, in run
    aug_rot=self.use_aug_rot)
  File "D:\2016-LIFT Learned Invariant Feature Points\tf-lift-master\datasets\lift.py", line 151, in next_batch
    ]] for _i in xrange(batch_size)
  File "D:\2016-LIFT Learned Invariant Feature Points\tf-lift-master\_**datasets\lift.py", line 151, in <listcomp>
    ]] for _i in xrange(batch_size)
IndexError: index 0 is out of bounds for axis 0 with size 0**__

I kept the one file name that is present in your example folder in all three split.h files (train, test, val). Then I ran into this error. 
Was the example just meant to show what preprocessed data looks like? 
It does have one file name and everything related to that file in the example folder. 
It should run.

**Comment by Jinniuzuo0516** [comment]
@kmyi dear prof. thanks for your  reply,i'll try to solve this problem.thanks a lot!

**Comment by Jinniuzuo0516** [comment]
@appyfizzA  hello sir,your link helps a lot,i'll try to solve this under the guide of the link.
