### ISSUE TITLE
lift training

### ISSUE THREAD

**Issue by lukino563** [cvlab-epfl/tf-lift#54]
hi a have problem running lift

`>> /home/fedora/Projects/LIFT/datasets/eccv2016/custom_types.py/143: waiting to obtain lock <<
>> obtained lock for posix system <<
train_data_dir = /home/fedora/Projects/LIFT/datasets/ECCV/piccadilly/
dump_data_dir = /home/fedora/Projects/LIFT/Temp/ECCV/piccadilly/train/8428245d927bae458f4f074c274fab6d/
dump_patch_dir = /home/fedora/Projects/LIFT/Temp/ECCV/piccadilly/train/8428245d927bae458f4f074c274fab6d/27ac55ebaf938a736d6027537eb0aa07/
tmp_patch_dir = /home/fedora/Projects/LIFT/Cache/ECCV/piccadilly/train/8428245d927bae458f4f074c274fab6d/27ac55ebaf938a736d6027537eb0aa07/
 -- train: Finished Processing Images!
 -- train: Reading dumps to figure out number of valid 1/2001Traceback (most recent call last):
  File "main.py", line 98, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/fedora/SDK/Anaconda/envs/LIFT/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/fedora/SDK/Anaconda/envs/LIFT/lib/python3.6/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/fedora/SDK/Anaconda/envs/LIFT/lib/python3.6/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "main.py", line 59, in main
    task = Trainer(config, rng)
  File "/home/fedora/Projects/LIFT/trainer.py", line 71, in __init__
    self.dataset = Dataset(self.config, rng)
  File "/home/fedora/Projects/LIFT/datasets/lift.py", line 85, in __init__
    self.data_wrapper = self.data_module.Wrapper(config, rng)
  File "/home/fedora/Projects/LIFT/datasets/eccv2016/wrapper.py", line 107, in __init__
    old_data = old_impl.data_obj(param, task)
  File "/home/fedora/Projects/LIFT/datasets/eccv2016/eccv.py", line 242, in __init__
    self.load_data(param, mode)
  File "/home/fedora/Projects/LIFT/datasets/eccv2016/eccv.py", line 270, in load_data
    cur_data = self.load_data_for_set(pathconf, param, mode)
  File "/home/fedora/Projects/LIFT/datasets/eccv2016/eccv.py", line 475, in load_data_for_set
    with h5py.File(final_dump_file_name, "r") as dump_file:
  File "/home/fedora/SDK/Anaconda/envs/LIFT/lib/python3.6/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/home/fedora/SDK/Anaconda/envs/LIFT/lib/python3.6/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/home/fedora/Projects/LIFT/Cache/ECCV/piccadilly/train/8428245d927bae458f4f074c274fab6d/27ac55ebaf938a736d6027537eb0aa07/1062837605_d2ccc880bf_o.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
`

dont know where is problem, directory exists

**Comment by kmyi** [comment]
Hi,

I think the training code is looking for the training file `1062837605_d2ccc880bf_o.h5`, which I don't think we provide. Note that the training code is released for mostly referential purposes, and the individual SfM models etc we do not provide (too big, and we've moved to different institutions)

Thanks,
Kwang
